provider:
  name: openfaas
functions:
  helloworld:
    lang: node
    handler: ./helloworld
    image: feri/helloworld:latest
  NodeHelloEnv:
    lang: node
    handler: ./NodeHelloEnv
    image: feri/NodeHelloEnv:latest
