provider:
  name: openfaas
functions:
  helloworld:
    lang: node
    handler: ./helloworld
    image: feri/helloworld:latest
  nodeinfo:
    lang: node
    handler: ./nodeinfo
    image: feri/nodeinfo:latest
  nodejs1:
    lang: node
    handler: ./nodejs1
    image: nodejs1:latest
  nodejs2:
    lang: node
    handler: ./nodejs2
    image: nodejs2:latest
