provider:
  name: openfaas
functions:
  helloworld:
    lang: node
    handler: ./helloworld
    image: feri/helloworld:latest
  NodeHelloEnv:
    lang: node
    handler: ./NodeHelloEnv
    image: feri/NodeHelloEnv:latest
  nodeinfo:
    lang: node
    handler: ./nodeinfo
    image: feri/nodeinfo:latest
  pwgen:
    lang: dockerfile
    image: functions/pwgen:latest

    